CREATE TABLE Job (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    json_data CLOB
);

INSERT INTO Job (id, json_data) VALUES ('JOB1234', '{"id": "JOB1234", "state": "Open", "address": {"streetName": "Main St", "streetNumber": "123", "city": "New York", "province": "NY", "postalCode": "10001"}, "customer": {"firstName": "John", "lastName": "Doe", "contactNumber": "john.doe@example.com", "phoneNumbers": ["123-456-7890"], "address": {"streetName": "Main St", "streetNumber": "123", "city": "New York", "province": "NY", "postalCode": "10001"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB5678', '{"id": "JOB5678", "state": "In Progress", "address": {"streetName": "Market St", "streetNumber": "456", "city": "San Francisco", "province": "CA", "postalCode": "94105"}, "customer": {"firstName": "Jane", "lastName": "Smith", "contactNumber": "jane.smith@example.com", "phoneNumbers": ["098-765-4321"], "address": {"streetName": "Market St", "streetNumber": "456", "city": "San Francisco", "province": "CA", "postalCode": "94105"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9101', '{"id": "JOB9101", "state": "Closed", "address": {"streetName": "Broadway", "streetNumber": "789", "city": "Chicago", "province": "IL", "postalCode": "60601"}, "customer": {"firstName": "Jim", "lastName": "Brown", "contactNumber": "jim.brown@example.com", "phoneNumbers": ["555-555-5555"], "address": {"streetName": "Broadway", "streetNumber": "789", "city": "Chicago", "province": "IL", "postalCode": "60601"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9102', '{"id": "JOB9102", "state": "Open", "address": {"streetName": "Rue Sherbrooke", "streetNumber": "1000", "city": "Montreal", "province": "QC", "postalCode": "H3A 0A1"}, "customer": {"firstName": "Alice", "lastName": "Tremblay", "contactNumber": "alice.tremblay@example.com", "phoneNumbers": ["514-123-4567"], "address": {"streetName": "Rue Sherbrooke", "streetNumber": "1000", "city": "Montreal", "province": "QC", "postalCode": "H3A 0A1"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9103', '{"id": "JOB9103", "state": "In Progress", "address": {"streetName": "Yonge Street", "streetNumber": "200", "city": "Toronto", "province": "ON", "postalCode": "M5G 2C6"}, "customer": {"firstName": "Bob", "lastName": "Lee", "contactNumber": "bob.lee@example.com", "phoneNumbers": ["416-987-6543"], "address": {"streetName": "Yonge Street", "streetNumber": "200", "city": "Toronto", "province": "ON", "postalCode": "M5G 2C6"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9104', '{"id": "JOB9104", "state": "Closed", "address": {"streetName": "Granville St", "streetNumber": "300", "city": "Vancouver", "province": "BC", "postalCode": "V6C 1S4"}, "customer": {"firstName": "Charlie", "lastName": "Singh", "contactNumber": "charlie.singh@example.com", "phoneNumbers": ["604-555-1212"], "address": {"streetName": "Granville St", "streetNumber": "300", "city": "Vancouver", "province": "BC", "postalCode": "V6C 1S4"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9105', '{"id": "JOB9105", "state": "Open", "address": {"streetName": "17th Ave", "streetNumber": "400", "city": "Calgary", "province": "AB", "postalCode": "T2S 0A5"}, "customer": {"firstName": "Diana", "lastName": "Nguyen", "contactNumber": "diana.nguyen@example.com", "phoneNumbers": ["403-222-3456"], "address": {"streetName": "17th Ave", "streetNumber": "400", "city": "Calgary", "province": "AB", "postalCode": "T2S 0A5"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9106', '{"id": "JOB9106", "state": "In Progress", "address": {"streetName": "Portage Ave", "streetNumber": "500", "city": "Winnipeg", "province": "MB", "postalCode": "R3C 0A7"}, "customer": {"firstName": "Ethan", "lastName": "McDonald", "contactNumber": "ethan.mcdonald@example.com", "phoneNumbers": ["204-949-2000"], "address": {"streetName": "Portage Ave", "streetNumber": "500", "city": "Winnipeg", "province": "MB", "postalCode": "R3C 0A7"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9107', '{"id": "JOB9107", "state": "Closed", "address": {"streetName": "Saskatchewan Dr", "streetNumber": "600", "city": "Saskatoon", "province": "SK", "postalCode": "S7K 1J9"}, "customer": {"firstName": "Fiona", "lastName": "Clark", "contactNumber": "fiona.clark@example.com", "phoneNumbers": ["306-652-4000"], "address": {"streetName": "Saskatchewan Dr", "streetNumber": "600", "city": "Saskatoon", "province": "SK", "postalCode": "S7K 1J9"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9108', '{"id": "JOB9108", "state": "Open", "address": {"streetName": "Water St", "streetNumber": "700", "city": "St. John''s", "province": "NL", "postalCode": "A1C 1A1"}, "customer": {"firstName": "Grace", "lastName": "O''Connell", "contactNumber": "grace.oconnell@example.com", "phoneNumbers": ["709-722-2800"], "address": {"streetName": "Water St", "streetNumber": "700", "city": "St. John''s", "province": "NL", "postalCode": "A1C 1A1"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9109', '{"id": "JOB9109", "state": "In Progress", "address": {"streetName": "Queen St", "streetNumber": "800", "city": "Charlottetown", "province": "PE", "postalCode": "C1A 4A9"}, "customer": {"firstName": "Henry", "lastName": "MacLeod", "contactNumber": "henry.macleod@example.com", "phoneNumbers": ["902-368-4400"], "address": {"streetName": "Queen St", "streetNumber": "800", "city": "Charlottetown", "province": "PE", "postalCode": "C1A 4A9"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9110', '{"id": "JOB9110", "state": "Closed", "address": {"streetName": "Main St", "streetNumber": "900", "city": "Fredericton", "province": "NB", "postalCode": "E3B 5H1"}, "customer": {"firstName": "Ivy", "lastName": "LeBlanc", "contactNumber": "ivy.leblanc@example.com", "phoneNumbers": ["506-453-2200"], "address": {"streetName": "Main St", "streetNumber": "900", "city": "Fredericton", "province": "NB", "postalCode": "E3B 5H1"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9111', '{"id": "JOB9111", "state": "Open", "address": {"streetName": "Franklin Ave", "streetNumber": "1000", "city": "Yellowknife", "province": "NT", "postalCode": "X1A 2R3"}, "customer": {"firstName": "Jack", "lastName": "Cardinal", "contactNumber": "jack.cardinal@example.com", "phoneNumbers": ["867-873-7000"], "address": {"streetName": "Franklin Ave", "streetNumber": "1000", "city": "Yellowknife", "province": "NT", "postalCode": "X1A 2R3"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9112', '{"id": "JOB9112", "state": "In Progress", "address": {"streetName": "Main St", "streetNumber": "1100", "city": "Whitehorse", "province": "YT", "postalCode": "Y1A 2A7"}, "customer": {"firstName": "Kelly", "lastName": "Smith", "contactNumber": "kelly.smith@example.com", "phoneNumbers": ["867-667-5811"], "address": {"streetName": "Main St", "streetNumber": "1100", "city": "Whitehorse", "province": "YT", "postalCode": "Y1A 2A7"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9113', '{"id": "JOB9113", "state": "Closed", "address": {"streetName": "Apex Rd", "streetNumber": "1200", "city": "Iqaluit", "province": "NU", "postalCode": "X0A 0H0"}, "customer": {"firstName": "Liam", "lastName": "Angnakak", "contactNumber": "liam.angnakak@example.com", "phoneNumbers": ["867-979-4900"], "address": {"streetName": "Apex Rd", "streetNumber": "1200", "city": "Iqaluit", "province": "NU", "postalCode": "X0A 0H0"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9114', '{"id": "JOB9114", "state": "Open", "address": {"streetName": "Rue Saint-Denis", "streetNumber": "2000", "city": "Montreal", "province": "QC", "postalCode": "H2X 3K2"}, "customer": {"firstName": "Marie", "lastName": "Gagnon", "contactNumber": "marie.gagnon@example.com", "phoneNumbers": ["514-845-3000"], "address": {"streetName": "Rue Saint-Denis", "streetNumber": "2000", "city": "Montreal", "province": "QC", "postalCode": "H2X 3K2"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9115', '{"id": "JOB9115", "state": "In Progress", "address": {"streetName": "Bay Street", "streetNumber": "100", "city": "Toronto", "province": "ON", "postalCode": "M5J 2N8"}, "customer": {"firstName": "Noah", "lastName": "Brown", "contactNumber": "noah.brown@example.com", "phoneNumbers": ["416-367-9700"], "address": {"streetName": "Bay Street", "streetNumber": "100", "city": "Toronto", "province": "ON", "postalCode": "M5J 2N8"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9116', '{"id": "JOB9116", "state": "Closed", "address": {"streetName": "Robson Street", "streetNumber": "1100", "city": "Vancouver", "province": "BC", "postalCode": "V6E 1B5"}, "customer": {"firstName": "Olivia", "lastName": "Chen", "contactNumber": "olivia.chen@example.com", "phoneNumbers": ["604-683-2000"], "address": {"streetName": "Robson Street", "streetNumber": "1100", "city": "Vancouver", "province": "BC", "postalCode": "V6E 1B5"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9117', '{"id": "JOB9117", "state": "Open", "address": {"streetName": "Stephen Avenue", "streetNumber": "800", "city": "Calgary", "province": "AB", "postalCode": "T2C 2K8"}, "customer": {"firstName": "Peter", "lastName": "Anderson", "contactNumber": "peter.anderson@example.com", "phoneNumbers": ["403-268-1200"], "address": {"streetName": "Stephen Avenue", "streetNumber": "800", "city": "Calgary", "province": "AB", "postalCode": "T2C 2K8"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9118', '{"id": "JOB9118", "state": "In Progress", "address": {"streetName": "Osborne Street", "streetNumber": "900", "city": "Winnipeg", "province": "MB", "postalCode": "R3L 2B4"}, "customer": {"firstName": "Quinn", "lastName": "Sinclair", "contactNumber": "quinn.sinclair@example.com", "phoneNumbers": ["204-474-7400"], "address": {"streetName": "Osborne Street", "streetNumber": "900", "city": "Winnipeg", "province": "MB", "postalCode": "R3L 2B4"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9119', '{"id": "JOB9119", "state": "Closed", "address": {"streetName": "2nd Avenue North", "streetNumber": "400", "city": "Saskatoon", "province": "SK", "postalCode": "S7K 2C3"}, "customer": {"firstName": "Rachel", "lastName": "Johnstone", "contactNumber": "rachel.johnstone@example.com", "phoneNumbers": ["306-975-7700"], "address": {"streetName": "2nd Avenue North", "streetNumber": "400", "city": "Saskatoon", "province": "SK", "postalCode": "S7K 2C3"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9120', '{"id": "JOB9120", "state": "Open", "address": {"streetName": "Duckworth Street", "streetNumber": "200", "city": "St. John''s", "province": "NL", "postalCode": "A1C 5M2"}, "customer": {"firstName": "Samuel", "lastName": "Power", "contactNumber": "samuel.power@example.com", "phoneNumbers": ["709-739-6400"], "address": {"streetName": "Duckworth Street", "streetNumber": "200", "city": "St. John''s", "province": "NL", "postalCode": "A1C 5M2"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9121', '{"id": "JOB9121", "state": "In Progress", "address": {"streetName": "Grafton Street", "streetNumber": "100", "city": "Charlottetown", "province": "PE", "postalCode": "C1A 1K8"}, "customer": {"firstName": "Taylor", "lastName": "Campbell", "contactNumber": "taylor.campbell@example.com", "phoneNumbers": ["902-629-4000"], "address": {"streetName": "Grafton Street", "streetNumber": "100", "city": "Charlottetown", "province": "PE", "postalCode": "C1A 1K8"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9122', '{"id": "JOB9122", "state": "Closed", "address": {"streetName": "Queen Street", "streetNumber": "500", "city": "Fredericton", "province": "NB", "postalCode": "E3B 1B1"}, "customer": {"firstName": "Uma", "lastName": "Ouellette", "contactNumber": "uma.ouellette@example.com", "phoneNumbers": ["506-452-9500"], "address": {"streetName": "Queen Street", "streetNumber": "500", "city": "Fredericton", "province": "NB", "postalCode": "E3B 1B1"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9123', '{"id": "JOB9123", "state": "Open", "address": {"streetName": "50th Avenue", "streetNumber": "400", "city": "Yellowknife", "province": "NT", "postalCode": "X1A 1R6"}, "customer": {"firstName": "Victor", "lastName": "Erasmus", "contactNumber": "victor.erasmus@example.com", "phoneNumbers": ["867-766-3400"], "address": {"streetName": "50th Avenue", "streetNumber": "400", "city": "Yellowknife", "province": "NT", "postalCode": "X1A 1R6"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9124', '{"id": "JOB9124", "state": "In Progress", "address": {"streetName": "4th Avenue", "streetNumber": "300", "city": "Whitehorse", "province": "YT", "postalCode": "Y1A 1K1"}, "customer": {"firstName": "Wendy", "lastName": "Carlick", "contactNumber": "wendy.carlick@example.com", "phoneNumbers": ["867-668-8600"], "address": {"streetName": "4th Avenue", "streetNumber": "300", "city": "Whitehorse", "province": "YT", "postalCode": "Y1A 1K1"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9125', '{"id": "JOB9125", "state": "Closed", "address": {"streetName": "Queen Elizabeth Way", "streetNumber": "100", "city": "Iqaluit", "province": "NU", "postalCode": "X0A 0H0"}, "customer": {"firstName": "Xavier", "lastName": "Alookie", "contactNumber": "xavier.alookie@example.com", "phoneNumbers": ["867-975-6300"], "address": {"streetName": "Queen Elizabeth Way", "streetNumber": "100", "city": "Iqaluit", "province": "NU", "postalCode": "X0A 0H0"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9126', '{"id": "JOB9126", "state": "Open", "address": {"streetName": "Rue Sainte-Catherine", "streetNumber": "1200", "city": "Montreal", "province": "QC", "postalCode": "H3B 1B2"}, "customer": {"firstName": "Yvette", "lastName": "Dube", "contactNumber": "yvette.dube@example.com", "phoneNumbers": ["514-393-3300"], "address": {"streetName": "Rue Sainte-Catherine", "streetNumber": "1200", "city": "Montreal", "province": "QC", "postalCode": "H3B 1B2"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9127', '{"id": "JOB9127", "state": "In Progress", "address": {"streetName": "University Avenue", "streetNumber": "200", "city": "Toronto", "province": "ON", "postalCode": "M5G 2C6"}, "customer": {"firstName": "Zachary", "lastName": "Martin", "contactNumber": "zachary.martin@example.com", "phoneNumbers": ["416-595-1500"], "address": {"streetName": "University Avenue", "streetNumber": "200", "city": "Toronto", "province": "ON", "postalCode": "M5G 2C6"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9128', '{"id": "JOB9128", "state": "Closed", "address": {"streetName": "Georgia Street", "streetNumber": "800", "city": "Vancouver", "province": "BC", "postalCode": "V6C 2G7"}, "customer": {"firstName": "Amelia", "lastName": "Wilson", "contactNumber": "amelia.wilson@example.com", "phoneNumbers": ["604-669-2700"], "address": {"streetName": "Georgia Street", "streetNumber": "800", "city": "Vancouver", "province": "BC", "postalCode": "V6C 2G7"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9129', '{"id": "JOB9129", "state": "Open", "address": {"streetName": "8th Avenue", "streetNumber": "500", "city": "Calgary", "province": "AB", "postalCode": "T2P 1E2"}, "customer": {"firstName": "Benjamin", "lastName": "Hall", "contactNumber": "benjamin.hall@example.com", "phoneNumbers": ["403-290-2800"], "address": {"streetName": "8th Avenue", "streetNumber": "500", "city": "Calgary", "province": "AB", "postalCode": "T2P 1E2"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9130', '{"id": "JOB9130", "state": "In Progress", "address": {"streetName": "Main Street", "streetNumber": "200", "city": "Winnipeg", "province": "MB", "postalCode": "R3C 1A8"}, "customer": {"firstName": "Charlotte", "lastName": "Green", "contactNumber": "charlotte.green@example.com", "phoneNumbers": ["204-942-0300"], "address": {"streetName": "Main Street", "streetNumber": "200", "city": "Winnipeg", "province": "MB", "postalCode": "R3C 1A8"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9131', '{"id": "JOB9131", "state": "Closed", "address": {"streetName": "Spadina Crescent", "streetNumber": "100", "city": "Saskatoon", "province": "SK", "postalCode": "S7K 3G6"}, "customer": {"firstName": "Daniel", "lastName": "White", "contactNumber": "daniel.white@example.com", "phoneNumbers": ["306-244-2100"], "address": {"streetName": "Spadina Crescent", "streetNumber": "100", "city": "Saskatoon", "province": "SK", "postalCode": "S7K 3G6"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9132', '{"id": "JOB9132", "state": "Open", "address": {"streetName": "Water Street", "streetNumber": "300", "city": "St. John''s", "province": "NL", "postalCode": "A1C 1B8"}, "customer": {"firstName": "Emily", "lastName": "Black", "contactNumber": "emily.black@example.com", "phoneNumbers": ["709-753-8200"], "address": {"streetName": "Water Street", "streetNumber": "300", "city": "St. John''s", "province": "NL", "postalCode": "A1C 1B8"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9133', '{"id": "JOB9133", "state": "In Progress", "address": {"streetName": "Great George Street", "streetNumber": "200", "city": "Charlottetown", "province": "PE", "postalCode": "C1A 4K2"}, "customer": {"firstName": "Finn", "lastName": "Gray", "contactNumber": "finn.gray@example.com", "phoneNumbers": ["902-892-3500"], "address": {"streetName": "Great George Street", "streetNumber": "200", "city": "Charlottetown", "province": "PE", "postalCode": "C1A 4K2"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9134', '{"id": "JOB9134", "state": "Closed", "address": {"streetName": "York Street", "streetNumber": "100", "city": "Fredericton", "province": "NB", "postalCode": "E3B 3N6"}, "customer": {"firstName": "Grace", "lastName": "Blue", "contactNumber": "grace.blue@example.com", "phoneNumbers": ["506-458-8500"], "address": {"streetName": "York Street", "streetNumber": "100", "city": "Fredericton", "province": "NB", "postalCode": "E3B 3N6"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9135', '{"id": "JOB9135", "state": "Open", "address": {"streetName": "Franklin Avenue", "streetNumber": "500", "city": "Yellowknife", "province": "NT", "postalCode": "X1A 2N4"}, "customer": {"firstName": "Henry", "lastName": "Red", "contactNumber": "henry.red@example.com", "phoneNumbers": ["867-873-4400"], "address": {"streetName": "Franklin Avenue", "streetNumber": "500", "city": "Yellowknife", "province": "NT", "postalCode": "X1A 2N4"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9136', '{"id": "JOB9136", "state": "In Progress", "address": {"streetName": "Main Street", "streetNumber": "400", "city": "Whitehorse", "province": "YT", "postalCode": "Y1A 2B1"}, "customer": {"firstName": "Isabelle", "lastName": "Purple", "contactNumber": "isabelle.purple@example.com", "phoneNumbers": ["867-667-6600"], "address": {"streetName": "Main Street", "streetNumber": "400", "city": "Whitehorse", "province": "YT", "postalCode": "Y1A 2B1"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9137', '{"id": "JOB9137", "state": "Closed", "address": {"streetName": "Federal Road", "streetNumber": "200", "city": "Iqaluit", "province": "NU", "postalCode": "X0A 0H0"}, "customer": {"firstName": "Jack", "lastName": "Orange", "contactNumber": "jack.orange@example.com", "phoneNumbers": ["867-979-5200"], "address": {"streetName": "Federal Road", "streetNumber": "200", "city": "Iqaluit", "province": "NU", "postalCode": "X0A 0H0"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9138', '{"id": "JOB9138", "state": "Open", "address": {"streetName": "Sherbrooke Street", "streetNumber": "1500", "city": "Montreal", "province": "QC", "postalCode": "H3G 1M8"}, "customer": {"firstName": "Kate", "lastName": "Yellow", "contactNumber": "kate.yellow@example.com", "phoneNumbers": ["514-848-2424"], "address": {"streetName": "Sherbrooke Street", "streetNumber": "1500", "city": "Montreal", "province": "QC", "postalCode": "H3G 1M8"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9139', '{"id": "JOB9139", "state": "In Progress", "address": {"streetName": "Queen Street West", "streetNumber": "300", "city": "Toronto", "province": "ON", "postalCode": "M5V 2A2"}, "customer": {"firstName": "Liam", "lastName": "Lime", "contactNumber": "liam.lime@example.com", "phoneNumbers": ["416-979-5000"], "address": {"streetName": "Queen Street West", "streetNumber": "300", "city": "Toronto", "province": "ON", "postalCode": "M5V 2A2"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9140', '{"id": "JOB9140", "state": "Closed", "address": {"streetName": "Davie Street", "streetNumber": "1000", "city": "Vancouver", "province": "BC", "postalCode": "V6E 1T5"}, "customer": {"firstName": "Mia", "lastName": "Teal", "contactNumber": "mia.teal@example.com", "phoneNumbers": ["604-689-1100"], "address": {"streetName": "Davie Street", "streetNumber": "1000", "city": "Vancouver", "province": "BC", "postalCode": "V6E 1T5"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9141', '{"id": "JOB9141", "state": "Open", "address": {"streetName": "17th Avenue SW", "streetNumber": "600", "city": "Calgary", "province": "AB", "postalCode": "T2S 2T2"}, "customer": {"firstName": "Noah", "lastName": "Aqua", "contactNumber": "noah.aqua@example.com", "phoneNumbers": ["403-228-1100"], "address": {"streetName": "17th Avenue SW", "streetNumber": "600", "city": "Calgary", "province": "AB", "postalCode": "T2S 2T2"}}}');
INSERT INTO Job (id, json_data) VALUES ('JOB9142', '{"id": "JOB9142", "state": "In Progress", "address": {"streetName": "Corydon Avenue", "streetNumber": "200", "city": "Winnipeg", "province": "MB", "postalCode": "R3M 0W4"}, "customer": {"firstName": "Olivia", "lastName": "Navy", "contactNumber": "olivia.navy@example.com", "phoneNumbers": ["204-452-3300"], "address": {"streetName": "Corydon Avenue", "streetNumber": "200", "city": "Winnipeg", "province": "MB", "postalCode": "R3M 0W4"}}}');
