import type { Technician } from "src/types/Technician";

export const getTechniciansResponse: Technician[] = [
  {
    firstName: "John",
    lastName: "Doe",
    id: "TECH1243",
    skills: ["Wireless", "Fiber"],
    phoneNumber: "123-456-7890",
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    id: "TECH2645",
    skills: ["Cable", "Fiber"],
    phoneNumber: "098-765-4321",
  },
  {
    firstName: "Jim",
    lastName: "Brown",
    id: "TECH5809",
    skills: ["Cable", "Wireless"],
    phoneNumber: "555-555-5555",
  },
  {
    firstName: "Alice",
    lastName: "Lee",
    id: "TECH5810",
    skills: ["Wireless", "Hardware"],
    phoneNumber: "111-222-3333",
  },
  {
    firstName: "Bob",
    lastName: "Kim",
    id: "TECH5811",
    skills: ["Fiber", "Software"],
    phoneNumber: "444-555-6666",
  },
  {
    firstName: "Charlie",
    lastName: "Chen",
    id: "TECH5812",
    skills: ["Cable", "Hardware"],
    phoneNumber: "777-888-9999",
  },
  {
    firstName: "David",
    lastName: "Garcia",
    id: "TECH5813",
    skills: ["Wireless", "Software"],
    phoneNumber: "101-112-1314",
  },
  {
    firstName: "Eve",
    lastName: "Rodriguez",
    id: "TECH5814",
    skills: ["Fiber", "Hardware"],
    phoneNumber: "151-617-1819",
  },
  {
    firstName: "Fred",
    lastName: "Wilson",
    id: "TECH5815",
    skills: ["Cable", "Software"],
    phoneNumber: "202-223-2425",
  },
  {
    firstName: "Ginny",
    lastName: "Martinez",
    id: "TECH5816",
    skills: ["Wireless", "Fiber"],
    phoneNumber: "262-728-2930",
  },
  {
    firstName: "Harry",
    lastName: "Anderson",
    id: "TECH5817",
    skills: ["Hardware", "Software"],
    phoneNumber: "313-334-3536",
  },
  {
    firstName: "Ivy",
    lastName: "Thomas",
    id: "TECH5818",
    skills: ["Cable", "Wireless"],
    phoneNumber: "373-839-4041",
  },
  {
    firstName: "Jack",
    lastName: "Jackson",
    id: "TECH5819",
    skills: ["Fiber", "Hardware"],
    phoneNumber: "424-445-4647",
  },
  {
    firstName: "Kelly",
    lastName: "White",
    id: "TECH5820",
    skills: ["Software", "Cable"],
    phoneNumber: "484-950-5152",
  },
  {
    firstName: "Larry",
    lastName: "Harris",
    id: "TECH5821",
    skills: ["Wireless", "Fiber"],
    phoneNumber: "535-556-5758",
  },
  {
    firstName: "Mia",
    lastName: "Martin",
    id: "TECH5822",
    skills: ["Hardware", "Software"],
    phoneNumber: "595-667-6869",
  },
  {
    firstName: "Noah",
    lastName: "Wright",
    id: "TECH5823",
    skills: ["Cable", "Wireless"],
    phoneNumber: "646-778-7980",
  },
  {
    firstName: "Olivia",
    lastName: "Hall",
    id: "TECH5824",
    skills: ["Fiber", "Hardware"],
    phoneNumber: "707-889-9091",
  },
  {
    firstName: "Peter",
    lastName: "Allen",
    id: "TECH5825",
    skills: ["Software", "Cable"],
    phoneNumber: "757-990-0102",
  },
  {
    firstName: "Quinn",
    lastName: "King",
    id: "TECH5826",
    skills: ["Wireless", "Fiber"],
    phoneNumber: "818-101-1213",
  },
  {
    firstName: "Rachel",
    lastName: "Baker",
    id: "TECH5827",
    skills: ["Hardware", "Software"],
    phoneNumber: "868-212-2324",
  },
  {
    firstName: "Sam",
    lastName: "Clark",
    id: "TECH5828",
    skills: ["Cable", "Wireless"],
    phoneNumber: "929-323-3435",
  },
  {
    firstName: "Tina",
    lastName: "Lewis",
    id: "TECH5829",
    skills: ["Fiber", "Hardware"],
    phoneNumber: "979-434-4546",
  },
  {
    firstName: "Uma",
    lastName: "Hill",
    id: "TECH5830",
    skills: ["Software", "Cable"],
    phoneNumber: "030-545-5657",
  },
  {
    firstName: "Victor",
    lastName: "Green",
    id: "TECH5831",
    skills: ["Wireless", "Fiber"],
    phoneNumber: "080-656-6768",
  },
  {
    firstName: "Wendy",
    lastName: "Scott",
    id: "TECH5832",
    skills: ["Hardware", "Software"],
    phoneNumber: "131-767-7879",
  },
  {
    firstName: "Xander",
    lastName: "Young",
    id: "TECH5833",
    skills: ["Cable", "Wireless"],
    phoneNumber: "181-878-8990",
  },
  {
    firstName: "Yasmine",
    lastName: "Lopez",
    id: "TECH5834",
    skills: ["Fiber", "Hardware"],
    phoneNumber: "232-989-0101",
  },
  {
    firstName: "Zach",
    lastName: "Adams",
    id: "TECH5835",
    skills: ["Software", "Cable"],
    phoneNumber: "282-010-1212",
  },
  {
    firstName: "Amy",
    lastName: "Gonzalez",
    id: "TECH5836",
    skills: ["Wireless", "Fiber"],
    phoneNumber: "333-121-2323",
  },
  {
    firstName: "Ben",
    lastName: "Perez",
    id: "TECH5837",
    skills: ["Hardware", "Software"],
    phoneNumber: "383-232-3434",
  },
  {
    firstName: "Cathy",
    lastName: "Reed",
    id: "TECH5838",
    skills: ["Cable", "Wireless"],
    phoneNumber: "434-343-4545",
  },
  {
    firstName: "Dan",
    lastName: "Barnes",
    id: "TECH5839",
    skills: ["Fiber", "Hardware"],
    phoneNumber: "484-454-5656",
  },
  {
    firstName: "Erin",
    lastName: "Gray",
    id: "TECH5840",
    skills: ["Software", "Cable"],
    phoneNumber: "535-565-6767",
  },
  {
    firstName: "Frank",
    lastName: "James",
    id: "TECH5841",
    skills: ["Wireless", "Fiber"],
    phoneNumber: "585-676-7878",
  },
  {
    firstName: "Grace",
    lastName: "Long",
    id: "TECH5842",
    skills: ["Hardware", "Software"],
    phoneNumber: "636-787-8989",
  },
  {
    firstName: "Hank",
    lastName: "Perry",
    id: "TECH5843",
    skills: ["Cable", "Wireless"],
    phoneNumber: "686-898-9090",
  },
  {
    firstName: "Ida",
    lastName: "Price",
    id: "TECH5844",
    skills: ["Fiber", "Hardware"],
    phoneNumber: "737-909-0101",
  },
  {
    firstName: "Jake",
    lastName: "Fisher",
    id: "TECH5845",
    skills: ["Software", "Cable"],
    phoneNumber: "787-010-1212",
  },
  {
    firstName: "Kara",
    lastName: "West",
    id: "TECH5846",
    skills: ["Wireless", "Fiber"],
    phoneNumber: "838-121-2323",
  },
  {
    firstName: "Leo",
    lastName: "Cole",
    id: "TECH5847",
    skills: ["Hardware", "Software"],
    phoneNumber: "888-232-3434",
  },
  {
    firstName: "Mona",
    lastName: "Ford",
    id: "TECH5848",
    skills: ["Cable", "Wireless"],
    phoneNumber: "939-343-4545",
  },
  {
    firstName: "Ned",
    lastName: "Rice",
    id: "TECH5849",
    skills: ["Fiber", "Hardware"],
    phoneNumber: "989-454-5656",
  },
  {
    firstName: "Opal",
    lastName: "Sharp",
    id: "TECH5850",
    skills: ["Software", "Cable"],
    phoneNumber: "040-565-6767",
  },
  {
    firstName: "Paul",
    lastName: "Stone",
    id: "TECH5851",
    skills: ["Wireless", "Fiber"],
    phoneNumber: "090-676-7878",
  },
  {
    firstName: "Rita",
    lastName: "Black",
    id: "TECH5852",
    skills: ["Hardware", "Software"],
    phoneNumber: "141-787-8989",
  },
  {
    firstName: "Seth",
    lastName: "Shaw",
    id: "TECH5853",
    skills: ["Cable", "Wireless"],
    phoneNumber: "191-898-9090",
  },
  {
    firstName: "Tara",
    lastName: "Lane",
    id: "TECH5854",
    skills: ["Fiber", "Hardware"],
    phoneNumber: "242-909-0101",
  },
  {
    firstName: "Vlad",
    lastName: "Parks",
    id: "TECH5855",
    skills: ["Software", "Cable"],
    phoneNumber: "292-010-1212",
  },
  {
    firstName: "Will",
    lastName: "Ross",
    id: "TECH5856",
    skills: ["Wireless", "Fiber"],
    phoneNumber: "343-121-2323",
  },
  {
    firstName: "Xena",
    lastName: "Burns",
    id: "TECH5857",
    skills: ["Hardware", "Software"],
    phoneNumber: "393-232-3434",
  },
  {
    firstName: "Yves",
    lastName: "Woods",
    id: "TECH5858",
    skills: ["Cable", "Wireless"],
    phoneNumber: "444-343-4545",
  },
  {
    firstName: "Zoe",
    lastName: "Bell",
    id: "TECH5859",
    skills: ["Fiber", "Hardware"],
    phoneNumber: "494-454-5656",
  },
];

export const getTechnicianResponse: Technician = {
  firstName: "John",
  lastName: "Doe",
  id: "TECH1243",
  skills: ["Wireless", "Fiber"],
  phoneNumber: "123-456-7890",
};
